site_name: KIT Prüfungsvorbereitung Datenbanken

theme:
  name: material
  language: de
  font: false
  favicon: bilder/favicon.png
  logo: bilder/logo.png

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - include-markdown
  - search

extra_css:
  - 'extra.css'

use_directory_urls: false

repo_url: https://github.com/herr-nm/MMBbS_KIT_PVDB

site_url: https://herr-nm.github.io/MMBbS_KIT_PVDB

nav:
    - Informationen zum Kurs: 'index.md'
    - Kapitel 01 - Modellunternehmen: 'kapitel_01.md'
    - Kapitel 02 - Grundlagen Datenhaltung: 'kapitel_02.md'
    - Kapitel 03 - Entwurf von Datenbanken & Normalisierung: 'kapitel_03.md'
    - Kapitel 04 - Entwurf von Datenbanken für MySQL: 'kapitel_04.md'
    - Kapitel 05 - Realisierung einer Datenbank mit MySQL: 'kapitel_05.md'
    - Kapitel 06 - MySQL - Einfache Datenabfragen mit SELECT: 'kapitel_06.md'
    